### ISSUE TITLE
No Geometry Optimization in Windows 10 - convert.py can't find obabel supplied with Avogadro2

### ISSUE THREAD

**Issue by Ineluki80** [matterhorn103/avo_xtb#4]
Version: Avogadro2 1.99 NightlyBuild 2024-02-12 w/ Windows 10

Problem: Geometries are not optimized 
Issue: convert.py :: find_openbabel() is not able to find OpenBabel supplied with Avogadro 2.
Solution:

The routine (line 44) checks if a file named "obabel" exists but under Windows the file is named "obabel.exe". 
This results in obabel_path being set to the default value "obabel".

This might sill work if Avogadro2 is in the path.
But, as in my case, the older Avogadro (1) might be in the path, too, supplying an old obabel version not supporting cjson, resulting in a (quiet) conversion error.

Therefore I suggest the following code change in convert.py

```
def find_openbabel():
    # Current directory upon execution of script seems to be the avo "prefix" directory
    prefix_dir = Path.cwd()
    # openbabel should be in the bin directory    
    if (prefix_dir / "bin" / "obabel").exists():
        obabel_path = prefix_dir / "bin" / "obabel"
    elif (prefix_dir / "bin" / "obabel.exe").exists():           # add this block to support
        obabel_path = prefix_dir / "bin" / "obabel.exe"          # exe files under windows
    else:
        obabel_path = "obabel"
    return obabel_path

obabel_path = find_openbabel()

```

**Comment by matterhorn103** [comment]
Good catch. I already added this as I am in the process of moving that code to `config.py` anyway, so that the user can set the path to Open Babel themselves.
